# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b1bc7f21847b30b4edb35cc71f36a6087977bfb49800f2316df21fd2a9d9adc8f44dbcfdbd043d9e837022f78bcbffdda308a0d7c07081d5ee77dbe43822e92

test:
  secret_key_base: 843d12bf9f73ebb094bedffdff17c2f94cae1b1f79d6ecb9d292fe066f30485c30ca3ce8667dc0bdc406aeaf4e77325b8908831a325f79b920a89a3a5c637a80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
